org.gradle.jvmargs=-Xmx2G

mod_id=emoji-type
mod_version=2.3.2-1.21.6
maven_group=dev.norbiros
minecraft_version=1.21.6
java_version=21

# Find versions in Linkie:
# https://linkie.shedaniel.me/dependencies

# Loader specific
fabric_minecraft_version_range=~1.21.6
# We don't have to use the most recent version for compatibility reasons
fabric_loader_version=0.16.14
yarn_mappings=1.21.6+build.1

neo_minecraft_version_range=[21.6, 22)
neoforge_version=21.6.0-beta
# The latest version from https://maven.architectury.dev/dev/architectury/yarn-mappings-patch-neoforge/
neoforge_yarn_mappings_patch=1.21+build.4

# Architectury
enabled_platforms=fabric,neoforge
architectury_version=17.0.6

# Mods versions
modmenu_version=15.0.0-beta.3
