# Find available versions on Linkie:
# https://linkie.shedaniel.me/dependencies

[versions]
minecraft = "26.2"
fabric-loader = "0.19.3"
neoforge = "26.2.0.7-beta"
modmenu = "20.0.0-alpha.1"
snakeyaml = "2.5"
shadow = "8.3.5"
architectury-plugin = "3.5.169"
architectury-loom = "1.17.487"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
architectury = { id = "architectury-plugin", version.ref = "architectury-plugin" }
architectury-loom = { id = "dev.architectury.loom-no-remap", version.ref = "architectury-loom" }
