# Find available versions on Linkie:
# https://linkie.shedaniel.me/dependencies

[versions]
minecraft = "26.1.2"
fabric-loader = "0.19.2"
neoforge = "21.10.55-beta"
neoforge-yarn-mappings-patch = "1.21+build.6"
modmenu = "18.0.0-alpha.8"
snakeyaml = "2.5"
fabric-loom = "1.16-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }

