name: release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get required Java version
        id: gradle-properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: java_version

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ steps.gradle-properties.outputs.java_version }}

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Publish to Modrinth and CurseForge
        run: ./gradlew publishMods --no-daemon
        env:
          CHANGELOG: ${{ github.event.release.body }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

      - name: Upload JARs to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            fabric/build/libs/emoji-type-*-fabric.jar
            neoforge/build/libs/emoji-type-*-neoforge.jar
